- hosts: localhost
  vars:
    pwd: /var/lib/jenkins/workspace/pp1_main
    
  remote_user: vagrant
  gather_facts: false

  tasks:
  - name: get local file name
    local_action: shell ls {{ pwd }}/target/*.jar
    register: file_name
    tags: test

  - name: upload
    tags:
     - upload
     - test
    copy:
     src: "{{ file_name.stdout }}"
     dest: ~/
    when: file_name.stdout != ""

  - name: start
    shell: "nohup java -jar ~/*.jar > log.out &"
    tags: start
